### ISSUE TITLE
Problem using Scholarly-Metadata

### ISSUE THREAD

**Issue by the-solipsist** [pandoc/lua-filters#108]
Hi. I'm trying to use scholarly-metadata.lua.  _Inter alia_, I have the following in my defaults.yaml:

```
---
metadata:
## General
  keywords: 'PANELFIT, GDPR, code of conduct'
## Citations and Citeproc
  reference-section-title: "References"
  bibliography: "coc.bib"
  citation-style: "chicago-fullnote-bibliography.csl"
  lang: 'en-GB'
  link-citations: true
  
filters: 
  - setdate/setdate.lua
  - scholarly-metadata/scholarly-metadata.lua
  - author-info-blocks/author-info-blocks.lua
...
```

I have used the example from expected.md in the scholarly-metadata folder:
```
---
author:
- id: Jane Doe
  institute:
  - 1
  - 2
  name: Jane Doe
  equal_contributor: "yes"
- id: John Q. Doe
  institute:
  - 1
  name: John Q. Doe
  equal_contributor: "yes"
- id: Peder Ås
  institute:
  - 1
  name: Peder Ås
- id: Juan Pérez
  institute:
  - 3
  name: Juan Pérez
- id: Max Mustermann
  name: Max Mustermann
institute:
- address: '23 Science Street, Eureka, Mississippi, USA'
  id: fosg
  index: 1
  name: Formatting Open Science Group
- id: fop
  index: 2
  name: Federation of Planets
- id: Acme Corporation
  index: 3
  name: Acme Corporation
...
```
However, I get this output:
![Screenshot from 2020-08-27 02-20-55](https://user-images.githubusercontent.com/3080824/91356480-5f575800-e80d-11ea-8b97-265b6ae12497.jpg)

What am I doing wrong?  

Also, if I use `indent: true`, then the alignment also gets messed up.

Also, is there any way of changing this into proper footnotes that appear in the footnote area in the bottom of the page?
