### ISSUE TITLE
reduce the space between authors to fit 5 authors in 1 line

### ISSUE THREAD

**Issue by DS-Rodrigues** [pandoc/lua-filters#198]
Hi,

Thanks again for creating this tool. I am using scholarly-metadata.lua and author-info-blocks.lua as per the example below:

```
---
title: "My title"
author:
  - Mario Modesto-Mata:
      email: paleomariomm@gmail.com
      institute: [astro, med]
      correspondence: true
  - name: Christopher
    institute: astro
  - name: Seaghán Mhartain
    institute: med
  - name: Rita Yuri Ynoue
    institute: astro
  - name: Test test
    institute: astro
institute:
  - astro: Instituto de Astronomía, Geofísica e Ciências Atmosféricas, Universidade de São Paulo
  - med: Faculdade de Medicina, Universidade de São Paulo
date: "1 October 2018"
output: 
  pdf_document: 
    number_sections: yes
    toc: no
    toc_depth: 4
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
  word_document:
    toc: yes
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
---
```

We have 5 authors, and right now one drops to the 2nd line. I think the space between authors could be reduced, is it possible to do that?

Thank you!
