### ISSUE TITLE
Author names are missing in the HTML using scholarly-metadata and author-info-blocks

### ISSUE THREAD

**Issue by zhengchencai** [pandoc/lua-filters#282]
Hi there,

I used scholarly-metadata.lua and author-info-blocks.lua to render a HTML, but the author names are missing. And "Authors" and "Affiliations" are empty, how can I fix this? Thanks a lot

```
---
title: "Testing Lua filters with Qmd"
author:
  - Jane Doe:
      institute:
        - federation
      equal_contributor: "yes"
      correspondence: "yes"
      email: jane.doe@example.com
  - John Q. Doe:
      institute: [federation, acme]
      equal_contributor: "yes"
  - Juan Pérez:
      institute: acme
institute:
  - federation: Federation of Planets
  - acme:
      name: Acme Corporation

format: html
filters: 
  - scholarly-metadata.lua
  - author-info-blocks.lua
---

```
![image](https://github.com/user-attachments/assets/957e1591-d299-450e-b519-a168cabe4f00)

If I add name in the author, 

```
---
title: "Testing Lua filters with Qmd"
author:
  - name: Jane Doe
    institute:
      - federation
    equal_contributor: "yes"
    correspondence: "yes"
    email: jane.doe@example.com
  - name: John Q. Doe
    institute: [federation, acme]
    equal_contributor: "yes"
  - name: Juan Pérez
    institute: acme
institute:
  - federation: Federation of Planets
  - acme:
      name: Acme Corporation

format: html
filters: 
  - scholarly-metadata.lua
  - author-info-blocks.lua
---

```

It became the following, 

![image](https://github.com/user-attachments/assets/13526703-259d-46f8-a63c-d9237cc1c4ee)
