### ISSUE TITLE
author-info-blocks filter in beamer presentation put affiliation and correspondence after TOC

### ISSUE THREAD

**Issue by raffaem** [pandoc/lua-filters#283]
Using the `author-info-blocks` in a beamer presentation puts the affiliation and correspondence of the authors after the TOC.

They should be before or even better in the title slide.

Here is a MWE both in source code and compiled PDF:

Compiled PDF: 
[test.pdf](https://github.com/user-attachments/files/16886494/test.pdf)

Source code:
```
---
title: "My Title"
date: \today
block-headings: true
toc: true
author:
    - Jane Joe:
          institute: unig
          equal_contributor: yes
          correspondence: yes
          email: "jane@joe.com"
    - John Joe:
          institute: unib
          equal_contributor: yes
          correspondence: yes
          email: "john@joe.com"
institute:
    - unig: "Best University"
    - unib: "Better University"
---

# Preface

## Preface

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

\newpage

# Introduction

## Intro 1
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Intro 2
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
