### ISSUE TITLE
[WARNING] Missing character: There is no ✉ (U+2709) (U+2709) in font [lmsans8-regular]:mapping=tex

### ISSUE THREAD

**Issue by raffaem** [pandoc/lua-filters#284]
Compiling into beamer with author-info-blocks gives these error messages:

```
[WARNING] Missing character: There is no ✉ (U+2709) (U+2709) in font [lmsans8-regular]:mapping=tex
```

Source code:
```
---
title: "My Title"
date: \today
block-headings: true
toc: true
author:
    - Jane Joe:
          institute: unig
          equal_contributor: yes
          correspondence: yes
          email: "jane@joe.com"
    - John Joe:
          institute: unib
          equal_contributor: yes
          correspondence: yes
          email: "john@joe.com"
institute:
    - unig: "Best University"
    - unib: "Better University"
---

# Preface

## Preface

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# Introduction

## Intro 1
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

## Intro 2
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
