### ISSUE TITLE
author-info-blocks doesn't work with pdf output

### ISSUE THREAD

**Issue by roberto-alexis-rodriguez** [pandoc/lua-filters#59]
I've been using the scholarly-metadata and author-info-blocks lua filters to generate docx files from markdown without issue.
When I tried to do the same for pdf, I received the following error:

```
Error running filter author-info-blocks.lua:
Error while running filter function: author-info-blocks.lua:168: attempt to call a nil value (method 'map')
```

A minimal-working-example that reproduces it is
```
---
title: A title
author:
  - author1:
      institute: [somewhere]
  - author2:
      institute: [somewhere]
      correspondence: "yes"
      email: email@example.edu
institute:
  - somewhere: Somewhereville, USA
---

# Header 1
aaaa

# Header 2
aaaa

## Subheader 2.1
ddddd
```

I tried to invoke pandoc as

```
pandoc -s temp.md -t latex -o temp.pdf --filter pandoc-citeproc --filter pandoc-crossref --lua-filter scholarly-metadata.lua --lua-filter author-info-blocks.lua

```

I am aware that there are other ways of inserting this type of metadata into pdf output, but I was curious if it was possible to do so in such a way that allows outputting both to docx and pdf without changing the yaml header.
