### ISSUE TITLE
Error 83 using scholarly-metadata.lua in YAML of Rmarkdown

### ISSUE THREAD

**Issue by katherinelauck** [pandoc/lua-filters#77]
I'm running Windows 10 and updated RStudio, pandoc, Rmarkdown, and the latest version of the .lua files in the following YAML. 

Trying to knit a .rmd with just the following in it, and scholarly-metadata.lua and author-info-blocks.lua in its directory,

```
---
title: "My title"
author: 
  - Katherine Lauck:
    email: kslauck@ucdavis.edu
    institute: [davis, pi]
    correspondence: true
  - name: Sarah L. Carroll
    institute: colorado
  - name: Elly Mufliati
    institute: [untan, pi]
  - name: Sadtata Noor Adirahmanta
    institute: bksda
  - name: Novia Sagita
    institute: pi
  - name: Siti Kartikawati
    institute: [untan, pi]
  - name: Adam Miller
    institute: pi
institute:
  - davis: Graduate Group in Ecology, University of California, Davis
  - pi: Planet Indonesia
  - untan: Fakultas Kehutanan, Universitas Tanjungpura
  - bksda: Balai Konservasi Sumber Daya Alam
  - colorado: Graduate Degree Program in Ecology, Colorado State University
output: 
  word_document:
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
\```

## Abstract

blah blah 
```
*note: delete the escape slash after the r setup block before running - sorry, I'm new to github formatting and couldn't figure out how to properly escape that triple tick without the slash remaining in the code block.*

Gives me:

`Error running filter scholarly-metadata.lua:
[string "scholarly-metadata.lua"]:7: unexpected symbol near '<'
Error: pandoc document conversion failed with error 83`

My interpretation of this error message is that pandoc is successfully opening and reading the .lua files but is expecting a different format. Commenting out the first filter gives the same error for the second filter.

**Comment by tarleb** [comment]
Thanks for the report! The issue seems to be caused by the first author block. Please try to either indent the lines under your name by two additional spaces

``` yaml
author: 
  - Katherine Lauck:
      email: kslauck@ucdavis.edu
      institute: [davis, pi]
      correspondence: true
```

or use `name` as for the other authors.

``` yaml
author: 
  - name: Katherine Lauck
    email: kslauck@ucdavis.edu
    institute: [davis, pi]
    correspondence: true
```
