### ISSUE TITLE
reseting numbering in multiple bibliographies as multiple articles

### ISSUE THREAD

**Issue by omarelashkar** [pandoc/lua-filters#81]
I'm trying to write multiple articles in rmarkdown. Here is my YAML setting:
```
---
bibliography_article1: article1.bib
bibliography_article2: article2.bib
bibliography_article3: article1.bib
bibliography_article4: article1.bib
csl: sage-vancouver.csl
output:
        html_document:
                pandoc_args: --lua-filter=multiple-bibliographies.lua
---
```
Note that vancouver style makes numbers for in-text citation as in this [link](https://en.wikipedia.org/wiki/Vancouver_system)

Now if I started writing my articles. like 
```
# Article 1
Some text[@authorx_refy]

## References 
::: {#refs_article1}
:::

# Article 2
Another text[@authory_refx]

## References 
::: {#refs_article2}
:::
```

Now the results will look like

# Article 1
Some text. 1

## References 
1. Authorx. Refx

# Article 2 
Another text. 2
1. Authory. Refy

Is there is a way to reset numbering after article 1, so article 2 starts counting from 1?

**Comment by tarleb** [comment]
It sounds like you'd want to use the *section-refs* filter. Just be aware that the filter has problems with certain citation styles (#38).

**Comment by omarelashkar** [comment]
@tarleb I'm not sure if it's going to work. I have tried it like this and It throws panadoc-citeproc error


```
---
title: omar
output:
  html_document:
    pandoc_args:
          - -F pandoc-citeproc
          - --lua-filter=sections-refs.lua
          - -M section-refs-level=2
bibliography: bib.bib
csl: vanc.csl
---

# Section One
One [@allen] 

# Section Two

two[@struss]

```

This gives error 
```
Error running filter  pandoc-citeproc:
Could not find executable  pandoc-citeproc
Error: pandoc document conversion failed with error 83
Execution halted
```

If the line of  `-F pandoc-citeproc` is removed, it knits with no change from no filter.
